Update containers to 20.0

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -11,6 +11,39 @@ echo ""
 echo "https://www.dyalog.com"
 echo ""
 
+if [ "x${SQL_SERVER}" != "x" ]; then
+    MAXTIME=60
+    C=1
+    echo "Waiting for database to come up at address ${SQL_SERVER}:${SQL_PORT}..."
+	while [ `/bin/nc ${SQL_SERVER} ${SQL_PORT} < /dev/null > /dev/null 2>&1; echo $?` != 0 ]; do
+        let C="$C + 1"
+        if [ $C -gt $MAXTIME ]; then
+        		echo "Database server failed after ${MAXTIME} seconds - Continuing..."
+            break;
+        fi
+	    sleep 1
+	done
+fi
+
+
+if env | grep "^SQL*" > /dev/null 2>&1 ; then
+    ## Set default database driver to MySQL
+    export SQL_DRIVER=${SQL_DRIVER:-MySQL}
+    export SQL_PORT=${SQL_PORT:-3309}
+    export SQL_DSN=${SQL_DSN:-$SQL_DATABASE}
+
+    cp /etc/odbc.ini /tmp/
+    cd /tmp
+
+    echo "Setting up SQAPL Connection"
+    env | awk -F"=" '/^SQL/ {print $1 " " $2}' | while read KEY VAL; do
+        sed -i "s/##${KEY}##/${VAL}/" /tmp/odbc.ini
+    done
+    cp /tmp/odbc.ini /etc/odbc.ini
+    rm /tmp/odbc.ini
+    cd -
+fi
+
 export DYALOG=/opt/mdyalog/{{DYALOG_RELEASE}}/64/unicode/
 export LD_LIBRARY_PATH="${DYALOG}:${LD_LIBRARY_PATH}"
 export WSPATH=$WSPATH:${DYALOG}/ws
@@ -18,6 +51,8 @@ export TERM=dumb
 export APL_TEXTINAPLCORE=${APL_TEXTINAPLCORE-1}
 export TRACE_ON_ERROR=0
 export SESSION_FILE="${SESSION_FILE-$DYALOG/default.dse}"
+export ODBCINI=/etc/odbc.ini
+export DOTNET_ROOT=/opt/dotnet
 
 if    [ "x${LOAD}" = "x" ] \
    && [ "x${CONFIGFILE}" = "x" ] \
@@ -57,3 +92,4 @@ if [ -n "${RIDE_INIT}" ]; then
 else
     $DYALOG/dyalog -s ${WS} $@
 fi
+
